/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mensa;

/**
 *
 * @author quevedo
 */
public class Opciones extends javax.swing.JFrame {

    /**
     * Creates new form Opciones
     */
    private Opciones() {
        initComponents();
        
        AzulClaro=new java.awt.Color(200, 200, 255);
    }

    public Opciones(Envio VEnvio,VistaPrevia VVistaPrevia){
        this();
        
        this.VEnvio=VEnvio;
        this.VVistaPrevia=VVistaPrevia;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgColorFondo = new javax.swing.ButtonGroup();
        cbDestinatario = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cbRemitente = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        rbFondoBlanco = new javax.swing.JRadioButton();
        rbFondoGris = new javax.swing.JRadioButton();
        rbFondoAzulClaro = new javax.swing.JRadioButton();

        cbDestinatario.setText("Destinatario");
        cbDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDestinatarioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Opciones:");

        cbRemitente.setText("Remitente");
        cbRemitente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRemitenteActionPerformed(evt);
            }
        });

        jLabel2.setText("Color de fondo:");

        rbFondoBlanco.setBackground(new java.awt.Color(255, 255, 255));
        bgColorFondo.add(rbFondoBlanco);
        rbFondoBlanco.setSelected(true);
        rbFondoBlanco.setText("Blanco");
        rbFondoBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFondoBlancoActionPerformed(evt);
            }
        });

        bgColorFondo.add(rbFondoGris);
        rbFondoGris.setText("Gris");
        rbFondoGris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFondoGrisActionPerformed(evt);
            }
        });

        bgColorFondo.add(rbFondoAzulClaro);
        rbFondoAzulClaro.setText("Azul claro");
        rbFondoAzulClaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFondoAzulClaroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbRemitente)
                            .addComponent(jLabel1)
                            .addComponent(cbDestinatario)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbFondoGris)
                            .addComponent(rbFondoBlanco)
                            .addComponent(rbFondoAzulClaro))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbDestinatario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRemitente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbFondoBlanco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbFondoGris)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbFondoAzulClaro)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDestinatarioActionPerformed
        // TODO add your handling code here:
        if(this.cbDestinatario.isSelected())
            VVistaPrevia.setDestinatario(VEnvio.tfDesNombreApellidos.getText());
        else
            VVistaPrevia.setDestinatario("");
    }//GEN-LAST:event_cbDestinatarioActionPerformed

    private void cbRemitenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRemitenteActionPerformed
        // TODO add your handling code here:
        if(this.cbRemitente.isSelected())
            VVistaPrevia.setRemitente(VEnvio.tfRemNombreApellidos.getText());
        else
            VVistaPrevia.setRemitente("");        
    }//GEN-LAST:event_cbRemitenteActionPerformed

    private void rbFondoBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFondoBlancoActionPerformed
        // TODO add your handling code here:
        VVistaPrevia.setColorFondo(java.awt.Color.WHITE);
    }//GEN-LAST:event_rbFondoBlancoActionPerformed

    private void rbFondoGrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFondoGrisActionPerformed
        // TODO add your handling code here:
        VVistaPrevia.setColorFondo(java.awt.Color.LIGHT_GRAY);
    }//GEN-LAST:event_rbFondoGrisActionPerformed

    private void rbFondoAzulClaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFondoAzulClaroActionPerformed
        // TODO add your handling code here:
        VVistaPrevia.setColorFondo(AzulClaro);
    }//GEN-LAST:event_rbFondoAzulClaroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opciones().setVisible(true);
            }
        });
    }

    private java.awt.Color AzulClaro;
    private Envio VEnvio;
    private VistaPrevia VVistaPrevia;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgColorFondo;
    private javax.swing.JCheckBox cbDestinatario;
    private javax.swing.JCheckBox cbRemitente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbFondoAzulClaro;
    private javax.swing.JRadioButton rbFondoBlanco;
    private javax.swing.JRadioButton rbFondoGris;
    // End of variables declaration//GEN-END:variables
}
