/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mensa;

import java.awt.Color;
import java.awt.Point;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class Envio extends javax.swing.JFrame {

    /**
     * Creates new form Envio
     */
    public Envio() {
        initComponents();
        contadorDeEventos=0;
        
        // Inicializar estructiras de datos de Detalles ruta
        FR=5;
        PosVertical=true;
        Mensaje="Vídrio";
        
        // Modelo para edición dinámica de la lista
        this.listRemitentes.setModel(new javax.swing.DefaultListModel());
        
        // Crear el objeto interfaz de la tarea
        TM=new TareaMensa(this);
        
        // Crear las ventanas
        VInicial=new Inicial(this);
        VVistaPrevia=new VistaPrevia();
        VOpciones=new Opciones(this,VVistaPrevia);
        DDetallesRuta=new dialogDetallesRuta();
        
        LFpLienzoFirma=(LienzoFirma)pLienzoFirma;
        PGpGrosor=(PanelGrosor)pGrosor;
        
        LFpLienzoFirma.setTrazoRadio(this.slGrosor.getValue());
        PGpGrosor.setRadio(slGrosor.getValue());
        
        LFpLienzoFirma.setGridBounds(new int[]{pLienzoFirma.getSize().width, pLienzoFirma.getSize().height});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGDestino = new javax.swing.ButtonGroup();
        bGOrganizacion = new javax.swing.ButtonGroup();
        bGDestinoTab = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfDesNombreApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbProvincial = new javax.swing.JRadioButton();
        rbNacional = new javax.swing.JRadioButton();
        rbInternacional = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbProvincia = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cbPais = new javax.swing.JComboBox();
        tfMunicipio = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tfRemNombreApellidos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfRemDireccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbOrganizacion = new javax.swing.JComboBox();
        checkClienteRegistrado = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        tfCodigoCliente = new javax.swing.JTextField();
        bCodigoClienteOK = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        listRemitentes = new javax.swing.JList();
        bAddRemitente = new javax.swing.JButton();
        bBorrarRemitente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        bOpciones = new javax.swing.JButton();
        bVistaPrevia = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taTextoEtiqueta = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        bCambiar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        bLeer = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        taDetallesRuta = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        lTarifa = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tfTarjeta = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbPagoAplazado = new javax.swing.JCheckBox();
        cbSeguro = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        comboMesesPagoAplazado = new javax.swing.JComboBox();
        bCalcularImporte = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taDetalleCalculo = new javax.swing.JTextArea();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taImporteDetallado = new javax.swing.JTextArea();
        pbCalculo = new javax.swing.JProgressBar();
        lImporteTotal = new javax.swing.JLabel();
        bRealizarPago = new javax.swing.JButton();
        bPararCalculo = new javax.swing.JButton();
        chkParticipa = new javax.swing.JCheckBox();
        spinNumero = new javax.swing.JSpinner();
        lblPremio1 = new javax.swing.JLabel();
        lblPremio2 = new javax.swing.JLabel();
        lblPremio3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BFirmaBorrar = new javax.swing.JButton();
        BFirmaAceptar = new javax.swing.JButton();
        pLienzoFirma = new LienzoFirma();
        slGrosor = new javax.swing.JSlider();
        jLabel19 = new javax.swing.JLabel();
        pGrosor = new PanelGrosor();
        sldHorizontal = new javax.swing.JSlider();
        sldVertical = new javax.swing.JSlider();
        jLabel20 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        rbmiProvincial = new javax.swing.JRadioButtonMenuItem();
        rbmiNacional = new javax.swing.JRadioButtonMenuItem();
        rbmiInternacional = new javax.swing.JRadioButtonMenuItem();
        menuOrganizacion = new javax.swing.JMenu();
        rbmiPersonal = new javax.swing.JRadioButtonMenuItem();
        rbmiEmpresarial = new javax.swing.JRadioButtonMenuItem();
        rbmiPublica = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mensa: Envío de mensjes");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Mensa: Envío de mensajes");

        jLabel2.setText("Nombre y apellidos:");

        jLabel3.setText("Dirección postal:");

        jLabel4.setText("Destino:");

        bGDestinoTab.add(rbProvincial);
        rbProvincial.setSelected(true);
        rbProvincial.setText("Provincial");
        rbProvincial.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbProvincialItemStateChanged(evt);
            }
        });
        rbProvincial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbProvincialActionPerformed(evt);
            }
        });

        bGDestinoTab.add(rbNacional);
        rbNacional.setText("Nacional");
        rbNacional.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbNacionalItemStateChanged(evt);
            }
        });
        rbNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNacionalActionPerformed(evt);
            }
        });

        bGDestinoTab.add(rbInternacional);
        rbInternacional.setText("Internacional");
        rbInternacional.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbInternacionalItemStateChanged(evt);
            }
        });
        rbInternacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbInternacionalActionPerformed(evt);
            }
        });

        jLabel5.setText("Municipio");

        jLabel6.setText("Provincia");

        cbProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Asturias", "Cantabria", "León", "Lugo" }));
        cbProvincia.setEnabled(false);

        jLabel7.setText("País");

        cbPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "España", "Francia", "Portugal" }));
        cbPais.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rbNacional)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbProvincia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rbInternacional)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfDesNombreApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(rbProvincial))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfMunicipio)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDesNombreApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbProvincial)
                    .addComponent(jLabel5)
                    .addComponent(tfMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNacional)
                    .addComponent(cbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rbInternacional)
                    .addComponent(cbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Destinatario", jPanel1);

        jLabel8.setText("Nombre y apellidos:");

        jLabel9.setText("Dirección postal:");

        jLabel10.setText("Organización:");

        cbOrganizacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Personal", "Empresarial", "Publica" }));
        cbOrganizacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbOrganizacionItemStateChanged(evt);
            }
        });

        checkClienteRegistrado.setText("Cliente registrado");
        checkClienteRegistrado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkClienteRegistradoItemStateChanged(evt);
            }
        });

        jLabel11.setText("Código de cliente");

        tfCodigoCliente.setEnabled(false);
        tfCodigoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCodigoClienteKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCodigoClienteKeyReleased(evt);
            }
        });

        bCodigoClienteOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mensa/iconCheck.png"))); // NOI18N
        bCodigoClienteOK.setEnabled(false);
        bCodigoClienteOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCodigoClienteOKActionPerformed(evt);
            }
        });

        listRemitentes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listRemitentes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listRemitentesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listRemitentes);

        bAddRemitente.setText("Añadir remitente");
        bAddRemitente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddRemitenteActionPerformed(evt);
            }
        });

        bBorrarRemitente.setText("Borrar remitente");
        bBorrarRemitente.setEnabled(false);
        bBorrarRemitente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarRemitenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfRemNombreApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfRemDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(checkClienteRegistrado)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bCodigoClienteOK, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(bAddRemitente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bBorrarRemitente)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkClienteRegistrado)
                        .addComponent(jLabel11)
                        .addComponent(tfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(bCodigoClienteOK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRemNombreApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfRemDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(cbOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddRemitente)
                    .addComponent(bBorrarRemitente))
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Remitente", jPanel4);

        bOpciones.setText("Opciones");
        bOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOpcionesActionPerformed(evt);
            }
        });

        bVistaPrevia.setText("Vista Previa");
        bVistaPrevia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVistaPreviaActionPerformed(evt);
            }
        });

        taTextoEtiqueta.setColumns(20);
        taTextoEtiqueta.setRows(5);
        taTextoEtiqueta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                taTextoEtiquetaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(taTextoEtiqueta);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(bOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                        .addComponent(bVistaPrevia, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bOpciones)
                    .addComponent(bVistaPrevia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("Etiqueta", jPanel5);

        bCambiar.setText("Cambiar");
        bCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCambiarActionPerformed(evt);
            }
        });

        jLabel12.setText("Detalles de ruta:");

        bLeer.setText("Leer");
        bLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLeerActionPerformed(evt);
            }
        });

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        taDetallesRuta.setEditable(false);
        taDetallesRuta.setColumns(20);
        taDetallesRuta.setRows(5);
        taDetallesRuta.setText("Frágil(0) - Resistente(10) : 5\n\nMantener posición vertical : Sí\n\nMensaje en paquete : Vídrio");
        jScrollPane3.setViewportView(taDetallesRuta);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel13.setText("Tarifa:");

        lTarifa.setBackground(new java.awt.Color(204, 204, 204));
        lTarifa.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lTarifa.setText("40€");
        lTarifa.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel12)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bCambiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 260, Short.MAX_VALUE))
                    .addComponent(lTarifa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bGuardar)
                            .addComponent(bCambiar)
                            .addComponent(bLeer))))
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Ruta y tarifa", jPanel3);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Tarifa: 40€");

        jLabel15.setText("Tarjeta:");

        cbPagoAplazado.setText("Gestión de pago aplazado");
        cbPagoAplazado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbPagoAplazadoStateChanged(evt);
            }
        });

        cbSeguro.setText("Seguro");

        jLabel16.setText("Meses:");

        comboMesesPagoAplazado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "6", "9" }));
        comboMesesPagoAplazado.setEnabled(false);

        bCalcularImporte.setText("Calcular Importe");
        bCalcularImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalcularImporteActionPerformed(evt);
            }
        });

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel17.setText("Detalle del cálculo:");

        taDetalleCalculo.setEditable(false);
        taDetalleCalculo.setColumns(20);
        taDetalleCalculo.setRows(5);
        jScrollPane4.setViewportView(taDetalleCalculo);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel18.setText("Importe detallado:");

        taImporteDetallado.setEditable(false);
        taImporteDetallado.setColumns(20);
        taImporteDetallado.setRows(5);
        jScrollPane5.setViewportView(taImporteDetallado);

        lImporteTotal.setBackground(new java.awt.Color(128, 128, 128));
        lImporteTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lImporteTotal.setText("Importe Total:");
        lImporteTotal.setOpaque(true);

        bRealizarPago.setText("Realizar pago");
        bRealizarPago.setEnabled(false);
        bRealizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRealizarPagoActionPerformed(evt);
            }
        });

        bPararCalculo.setText("Parar cálculo");
        bPararCalculo.setEnabled(false);
        bPararCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPararCalculoActionPerformed(evt);
            }
        });

        chkParticipa.setText("Participa en sorteo");
        chkParticipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkParticipaActionPerformed(evt);
            }
        });

        spinNumero.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));
        spinNumero.setEnabled(false);

        lblPremio1.setBackground(new java.awt.Color(0, 0, 0));
        lblPremio1.setOpaque(true);

        lblPremio2.setBackground(new java.awt.Color(0, 0, 0));
        lblPremio2.setOpaque(true);

        lblPremio3.setBackground(new java.awt.Color(0, 0, 0));
        lblPremio3.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfTarjeta))))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbSeguro)
                                .addComponent(cbPagoAplazado)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(jLabel16)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboMesesPagoAplazado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bCalcularImporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chkParticipa)
                                .addComponent(spinNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPremio1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(lblPremio2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(lblPremio3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bPararCalculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pbCalculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addComponent(jLabel18)
                    .addComponent(lImporteTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bRealizarPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(pbCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(26, 26, 26)
                                .addComponent(cbSeguro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbPagoAplazado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(comboMesesPagoAplazado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(chkParticipa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lImporteTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bRealizarPago)
                                    .addComponent(bPararCalculo)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPremio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPremio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPremio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(bCalcularImporte))))
                    .addComponent(jSeparator5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pago", jPanel6);

        BFirmaBorrar.setText("Borrar");
        BFirmaBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFirmaBorrarActionPerformed(evt);
            }
        });

        BFirmaAceptar.setText("Aceptar");
        BFirmaAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFirmaAceptarActionPerformed(evt);
            }
        });

        pLienzoFirma.setBackground(new java.awt.Color(255, 255, 255));
        pLienzoFirma.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pLienzoFirmaMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout pLienzoFirmaLayout = new javax.swing.GroupLayout(pLienzoFirma);
        pLienzoFirma.setLayout(pLienzoFirmaLayout);
        pLienzoFirmaLayout.setHorizontalGroup(
            pLienzoFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );
        pLienzoFirmaLayout.setVerticalGroup(
            pLienzoFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        slGrosor.setMajorTickSpacing(1);
        slGrosor.setMaximum(10);
        slGrosor.setMinimum(1);
        slGrosor.setValue(4);
        slGrosor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slGrosorStateChanged(evt);
            }
        });

        jLabel19.setText("Grosor");

        pGrosor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pGrosorLayout = new javax.swing.GroupLayout(pGrosor);
        pGrosor.setLayout(pGrosorLayout);
        pGrosorLayout.setHorizontalGroup(
            pGrosorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pGrosorLayout.setVerticalGroup(
            pGrosorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        sldHorizontal.setValue(0);
        sldHorizontal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldHorizontalStateChanged(evt);
            }
        });

        sldVertical.setValue(0);
        sldVertical.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldVerticalStateChanged(evt);
            }
        });

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Cuadrícula");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sldVertical, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(sldHorizontal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(BFirmaAceptar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BFirmaBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(slGrosor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(pGrosor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pLienzoFirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pLienzoFirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BFirmaBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addGap(2, 2, 2)
                        .addComponent(slGrosor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pGrosor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sldVertical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BFirmaAceptar)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Firma", jPanel2);

        jMenu1.setText("Envío");

        jMenuItem1.setText("Nuevo envío");
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Salir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Ámbito");

        jMenu4.setText("Destino");

        bGDestino.add(rbmiProvincial);
        rbmiProvincial.setSelected(true);
        rbmiProvincial.setText("Provincial");
        rbmiProvincial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmiProvincialActionPerformed(evt);
            }
        });
        jMenu4.add(rbmiProvincial);

        bGDestino.add(rbmiNacional);
        rbmiNacional.setText("Nacional");
        rbmiNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmiNacionalActionPerformed(evt);
            }
        });
        jMenu4.add(rbmiNacional);

        bGDestino.add(rbmiInternacional);
        rbmiInternacional.setText("Internacional");
        rbmiInternacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmiInternacionalActionPerformed(evt);
            }
        });
        jMenu4.add(rbmiInternacional);

        jMenu3.add(jMenu4);

        menuOrganizacion.setText("Organización");

        bGOrganizacion.add(rbmiPersonal);
        rbmiPersonal.setSelected(true);
        rbmiPersonal.setText("Personal");
        rbmiPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmiPersonalActionPerformed(evt);
            }
        });
        menuOrganizacion.add(rbmiPersonal);

        bGOrganizacion.add(rbmiEmpresarial);
        rbmiEmpresarial.setText("Empresarial");
        rbmiEmpresarial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmiEmpresarialActionPerformed(evt);
            }
        });
        menuOrganizacion.add(rbmiEmpresarial);

        bGOrganizacion.add(rbmiPublica);
        rbmiPublica.setText("Pública");
        rbmiPublica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmiPublicaActionPerformed(evt);
            }
        });
        menuOrganizacion.add(rbmiPublica);

        jMenu3.add(menuOrganizacion);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Condiciones");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Frágil");
        jMenu2.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Urgente");
        jMenu2.add(jCheckBoxMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jTabbedPane1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int contadorDeEventos;
    private void Traza(String msg)
    {
        contadorDeEventos=contadorDeEventos+1;
        System.out.println("Evento:"+contadorDeEventos+" "+msg);
    }
    
    private void rbmiNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmiNacionalActionPerformed
        // TODO add your handling code here:
        Traza("rbmiNacionalActionPerformed");
        this.rbNacional.setSelected(this.rbmiNacional.isSelected());
    }//GEN-LAST:event_rbmiNacionalActionPerformed

    private void rbmiProvincialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmiProvincialActionPerformed
        // TODO add your handling code here:
        Traza("rbmiProvincialActionPerformed");
        this.rbProvincial.setSelected(this.rbmiProvincial.isSelected());
    }//GEN-LAST:event_rbmiProvincialActionPerformed

    private void rbmiInternacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmiInternacionalActionPerformed
        // TODO add your handling code here:
        Traza("rbmiInternacionalActionPerformed");
        this.rbInternacional.setSelected(this.rbmiInternacional.isSelected());
    }//GEN-LAST:event_rbmiInternacionalActionPerformed

    private void rbProvincialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbProvincialActionPerformed
        // TODO add your handling code here:
        Traza("rbProvincialActionPerformed");
        this.rbmiProvincial.setSelected(this.rbProvincial.isSelected());
    }//GEN-LAST:event_rbProvincialActionPerformed

    private void rbNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNacionalActionPerformed
        // TODO add your handling code here:
        Traza("rbNacionalActionPerformed");
        this.rbmiNacional.setSelected(this.rbNacional.isSelected());
    }//GEN-LAST:event_rbNacionalActionPerformed

    private void rbInternacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInternacionalActionPerformed
        // TODO add your handling code here:
        Traza("rbInternacionalActionPerformed");
        this.rbmiInternacional.setSelected(this.rbInternacional.isSelected());
    }//GEN-LAST:event_rbInternacionalActionPerformed

    private void rbInternacionalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbInternacionalItemStateChanged
        // TODO add your handling code here:
        Traza("rbInternacionalItemStateChanged");
        this.cbPais.setEnabled(this.rbInternacional.isSelected());
    }//GEN-LAST:event_rbInternacionalItemStateChanged

    private void rbProvincialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbProvincialItemStateChanged
        // TODO add your handling code here:       
        Traza("rbProvincialItemStateChanged");
        MunicipioSetEnabled();       
    }//GEN-LAST:event_rbProvincialItemStateChanged

    private void rbNacionalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbNacionalItemStateChanged
        // TODO add your handling code here:    
        Traza("rbNacionalItemStateChanged");
        MunicipioSetEnabled();
        this.cbProvincia.setEnabled(this.rbNacional.isSelected());
    }//GEN-LAST:event_rbNacionalItemStateChanged

    private void checkClienteRegistradoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkClienteRegistradoItemStateChanged
        // TODO add your handling code here:
        boolean cr=this.checkClienteRegistrado.isSelected();
        this.tfCodigoCliente.setEnabled(cr);
        this.tfRemNombreApellidos.setEnabled(!cr);
        this.tfRemDireccion.setEnabled(!cr);
        this.cbOrganizacion.setEnabled(!cr);
        this.menuOrganizacion.setEnabled(!cr);
    }//GEN-LAST:event_checkClienteRegistradoItemStateChanged

    private void SincronizaCBOrganizacion(int posSel)
    {
        this.cbOrganizacion.setSelectedIndex(posSel);
    }
    
    private void rbmiPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmiPersonalActionPerformed
        // TODO add your handling code here:
        SincronizaCBOrganizacion(0);
    }//GEN-LAST:event_rbmiPersonalActionPerformed

    private void rbmiEmpresarialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmiEmpresarialActionPerformed
        // TODO add your handling code here:
        SincronizaCBOrganizacion(1);
    }//GEN-LAST:event_rbmiEmpresarialActionPerformed

    private void rbmiPublicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmiPublicaActionPerformed
        // TODO add your handling code here:
        SincronizaCBOrganizacion(2);
    }//GEN-LAST:event_rbmiPublicaActionPerformed

    private void cbOrganizacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbOrganizacionItemStateChanged
        // TODO add your handling code here:
        switch(this.cbOrganizacion.getSelectedIndex())
        {
            case 0: this.rbmiPersonal.setSelected(true); break;
            case 1: this.rbmiEmpresarial.setSelected(true); break;
            case 2: this.rbmiPublica.setSelected(true); break;
        }
    }//GEN-LAST:event_cbOrganizacionItemStateChanged

    private void tfCodigoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoClienteKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (c>='a' && c<='f') // Si c es minúscula, se pasa a muyúsculas
            c=(char)((int)c-(int)'a'+(int)'A');
   
        if (c>='A' && c<='F')
            evt.setKeyChar(c);
        else if (c>='0' && c<='9')
            evt.setKeyChar(c);
        else
            evt.setKeyChar('\0');
    }//GEN-LAST:event_tfCodigoClienteKeyTyped

    private void tfCodigoClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoClienteKeyReleased
        // TODO add your handling code here:
        boolean CCOK=false;
        String CC=this.tfCodigoCliente.getText();
        if (CC.length()==7)
        {
            char PriChar=CC.charAt(0);
            if (PriChar>='0' && PriChar<='9')
                CCOK=true;
        }
        this.bCodigoClienteOK.setEnabled(CCOK);
    }//GEN-LAST:event_tfCodigoClienteKeyReleased

    private void bCodigoClienteOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCodigoClienteOKActionPerformed
        // TODO add your handling code here:
        this.tfRemNombreApellidos.setText("Un nombre y apelidos cualquiera");
        this.tfRemDireccion.setText("Una dirección cualquiera");
        this.cbOrganizacion.setSelectedIndex(1); // Empresarial
    }//GEN-LAST:event_bCodigoClienteOKActionPerformed

    private void bAddRemitenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddRemitenteActionPerformed
        // TODO add your handling code here:

        // Crear la cadena a insertar
        String Pre="";
        switch(this.cbOrganizacion.getSelectedIndex())
        {
            case 0: Pre="Per"; break;
            case 1: Pre="Emp"; break;
            case 2: Pre="Pub"; break;                
        }
        String CI=Pre+": "+this.tfRemNombreApellidos.getText()+" ("+this.tfRemDireccion.getText()+") ";
        
        // Obtener el modelo
        javax.swing.DefaultListModel Model=(javax.swing.DefaultListModel)this.listRemitentes.getModel();
        
        // Insertar la cadena en el modelo
        Model.addElement(CI);
    }//GEN-LAST:event_bAddRemitenteActionPerformed

    private void bBorrarRemitenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarRemitenteActionPerformed
        // TODO add your handling code here:
        
        // Obtener el modelo
        javax.swing.DefaultListModel Model=(javax.swing.DefaultListModel)this.listRemitentes.getModel();
        
        int Si=this.listRemitentes.getSelectedIndex(); // Obtiene el índice de la posición a borrar
        if (Si>=0) // Hay una fila seleccionada
        {
            Model.removeElementAt(Si); // Borra el elemento
            // Mantener la selección en su posición
            if(Model.size()==Si) // Se ha borrado el último elemento
                this.listRemitentes.setSelectedIndex(Si-1);
            else
                this.listRemitentes.setSelectedIndex(Si);
        }
    }//GEN-LAST:event_bBorrarRemitenteActionPerformed

    private void listRemitentesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listRemitentesValueChanged
        // TODO add your handling code here:
        this.bBorrarRemitente.setEnabled(!this.listRemitentes.isSelectionEmpty());
    }//GEN-LAST:event_listRemitentesValueChanged

    private void bOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOpcionesActionPerformed
        // TODO add your handling code here:
        this.VOpciones.setVisible(true);
    }//GEN-LAST:event_bOpcionesActionPerformed

    private void bVistaPreviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVistaPreviaActionPerformed
        // TODO add your handling code here:
        this.VVistaPrevia.setVisible(true);
    }//GEN-LAST:event_bVistaPreviaActionPerformed

    
    private void taTextoEtiquetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taTextoEtiquetaKeyReleased
        // TODO add your handling code here:
        this.VVistaPrevia.setTexto(this.taTextoEtiqueta.getText());
    }//GEN-LAST:event_taTextoEtiquetaKeyReleased

    private void PintaDetallesRuta(){    
        String SDR="Frágil(0) - Resistente(10) : "+FR+"\n\n";

        SDR=SDR+"Mantener posición vertical : ";
        if(PosVertical)
            SDR=SDR+"Sí";
        else
            SDR=SDR+"No";
        SDR=SDR+"\n\n";

        SDR=SDR+"Mensaje en paquete : "+Mensaje;

        this.taDetallesRuta.setText(SDR);
    }
    
    private void bCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCambiarActionPerformed
        // TODO add your handling code here:
        if(this.DDetallesRuta.showDialog(FR,PosVertical,Mensaje)){
            FR=this.DDetallesRuta.getFR();
            PosVertical=this.DDetallesRuta.isPosVertical();
            Mensaje=this.DDetallesRuta.getMensaje();
            
            PintaDetallesRuta();
        }
    }//GEN-LAST:event_bCambiarActionPerformed

    private void bLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLeerActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser DOF=new javax.swing.JFileChooser();
        int Ret=DOF.showOpenDialog(null);
        if(Ret==javax.swing.JFileChooser.APPROVE_OPTION){
            int Ret2=javax.swing.JOptionPane.showConfirmDialog(null, 
                    "Se sobreescribirán los detalles de ruta con los alamcenados en\n"+DOF.getSelectedFile().getAbsolutePath()+"\n¿Quiere continuar?",
                    "Lectura de fichero de los detalles de ruta", 
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE);
            if(Ret2==javax.swing.JOptionPane.YES_OPTION){
                javax.swing.JOptionPane.showMessageDialog(null,"Se ha leído la información del fichero:\n"+DOF.getSelectedFile().getAbsolutePath(),
                        "Lectura de fichero", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_bLeerActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser DOF=new javax.swing.JFileChooser();
        int Ret=DOF.showSaveDialog(null);
        if(Ret==javax.swing.JFileChooser.APPROVE_OPTION){
            javax.swing.JOptionPane.showMessageDialog(null,"Se ha escrito la información en el fichero:\n"+DOF.getSelectedFile().getAbsolutePath(),
                        "Escritura en fichero", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bCalcularImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalcularImporteActionPerformed
        // TODO add your handling code here:
        lblPremio1.setBackground(Color.BLACK);
        lblPremio2.setBackground(Color.BLACK);
        lblPremio3.setBackground(Color.BLACK);
        // Dar valor al seguro
        TM.setSeguro(this.cbSeguro.isSelected());
        
        // Dar valor al pago aplazado
        if(this.cbPagoAplazado.isSelected()){
            int Meses=(this.comboMesesPagoAplazado.getSelectedIndex()+1)*3;
            TM.setPagoApazado(Meses);
        }else
            TM.setPagoApazado(-1);
        TM.setNumero((int) spinNumero.getValue());
        
        // Crear un hilo que lance la tarea
        Thread HiloBack=new Thread(){public void run(){Envio.TM.Run();}};        
        HiloBack.start(); // Lanzar el hilo (ejecutará Run)
        
    }//GEN-LAST:event_bCalcularImporteActionPerformed

    private void bPararCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPararCalculoActionPerformed
        // TODO add your handling code here:
        TM.setStop();
        this.bPararCalculo.setEnabled(false);
    }//GEN-LAST:event_bPararCalculoActionPerformed

    private void bRealizarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRealizarPagoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Pago efectuado", "Pago", JOptionPane.INFORMATION_MESSAGE);
        this.bRealizarPago.setEnabled(false);
    }//GEN-LAST:event_bRealizarPagoActionPerformed

    private void cbPagoAplazadoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbPagoAplazadoStateChanged
        // TODO add your handling code here:
        this.comboMesesPagoAplazado.setEnabled(this.cbPagoAplazado.isSelected());
    }//GEN-LAST:event_cbPagoAplazadoStateChanged

    private void pLienzoFirmaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLienzoFirmaMouseDragged
        // TODO add your handling code here:
        Point p=evt.getPoint();
        LFpLienzoFirma.insertaPunto(p);
        LFpLienzoFirma.repaint();
    }//GEN-LAST:event_pLienzoFirmaMouseDragged

    private void BFirmaBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFirmaBorrarActionPerformed
        // TODO add your handling code here:
        LFpLienzoFirma.borra();
        LFpLienzoFirma.repaint();
    }//GEN-LAST:event_BFirmaBorrarActionPerformed

    private void slGrosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slGrosorStateChanged
        // TODO add your handling code here:
        PGpGrosor.setRadio(this.slGrosor.getValue());
        LFpLienzoFirma.setTrazoRadio(this.slGrosor.getValue());
        PGpGrosor.repaint();
        LFpLienzoFirma.repaint();
    }//GEN-LAST:event_slGrosorStateChanged

    private void BFirmaAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFirmaAceptarActionPerformed
        // TODO add your handling code here:
        this.BFirmaBorrar.setEnabled(false);
        this.slGrosor.setEnabled(false);
        this.LFpLienzoFirma.setTrazoColor(Color.GREEN);
        this.LFpLienzoFirma.repaint();
    }//GEN-LAST:event_BFirmaAceptarActionPerformed

    private void chkParticipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkParticipaActionPerformed
        // TODO add your handling code here:
        if(chkParticipa.isSelected()){
            spinNumero.setEnabled(true);
            TM.setParticipa(true);            
        }else{
            spinNumero.setEnabled(false);
            TM.setParticipa(true);
        }
    }//GEN-LAST:event_chkParticipaActionPerformed

    private void sldHorizontalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldHorizontalStateChanged
        LFpLienzoFirma.setHorizontal(sldHorizontal.getValue());
        LFpLienzoFirma.repaint();
    }//GEN-LAST:event_sldHorizontalStateChanged

    private void sldVerticalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldVerticalStateChanged
        LFpLienzoFirma.setVertical(sldVertical.getValue());
        LFpLienzoFirma.repaint();
    }//GEN-LAST:event_sldVerticalStateChanged

    // Método que activa el textField de municipio solo si está activado el envío provincial o nacional
    private int cMSE=0;
    private void MunicipioSetEnabled()
    {
        cMSE=cMSE+1;
        // Se activará el municipio si es un envío provincial o nacional
        System.out.println("MunicipioSetEnabled "+cMSE+" "+(this.rbProvincial.isSelected() || this.rbNacional.isSelected()));
        this.tfMunicipio.setEnabled(this.rbProvincial.isSelected() || this.rbNacional.isSelected());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Envio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Envio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Envio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Envio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Envio().setVisible(false);
            }
        });
    }
    
    private Opciones VOpciones;
    private VistaPrevia VVistaPrevia;
    private Inicial VInicial;
    private dialogDetallesRuta DDetallesRuta;
    public static TareaMensa TM; 
    
    // Estructura de datos para Detalles de Envío
    private int FR;
    private boolean PosVertical;
    private String Mensaje;
    
    LienzoFirma LFpLienzoFirma;
    PanelGrosor PGpGrosor;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton BFirmaAceptar;
    javax.swing.JButton BFirmaBorrar;
    javax.swing.JButton bAddRemitente;
    javax.swing.JButton bBorrarRemitente;
    javax.swing.JButton bCalcularImporte;
    javax.swing.JButton bCambiar;
    javax.swing.JButton bCodigoClienteOK;
    javax.swing.ButtonGroup bGDestino;
    javax.swing.ButtonGroup bGDestinoTab;
    javax.swing.ButtonGroup bGOrganizacion;
    javax.swing.JButton bGuardar;
    javax.swing.JButton bLeer;
    javax.swing.JButton bOpciones;
    javax.swing.JButton bPararCalculo;
    javax.swing.JButton bRealizarPago;
    javax.swing.JButton bVistaPrevia;
    javax.swing.JComboBox cbOrganizacion;
    javax.swing.JCheckBox cbPagoAplazado;
    javax.swing.JComboBox cbPais;
    javax.swing.JComboBox cbProvincia;
    javax.swing.JCheckBox cbSeguro;
    javax.swing.JCheckBox checkClienteRegistrado;
    javax.swing.JCheckBox chkParticipa;
    javax.swing.JComboBox comboMesesPagoAplazado;
    javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel11;
    javax.swing.JLabel jLabel12;
    javax.swing.JLabel jLabel13;
    javax.swing.JLabel jLabel14;
    javax.swing.JLabel jLabel15;
    javax.swing.JLabel jLabel16;
    javax.swing.JLabel jLabel17;
    javax.swing.JLabel jLabel18;
    javax.swing.JLabel jLabel19;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel20;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel8;
    javax.swing.JLabel jLabel9;
    javax.swing.JMenu jMenu1;
    javax.swing.JMenu jMenu2;
    javax.swing.JMenu jMenu3;
    javax.swing.JMenu jMenu4;
    javax.swing.JMenuBar jMenuBar1;
    javax.swing.JMenuItem jMenuItem1;
    javax.swing.JMenuItem jMenuItem2;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel3;
    javax.swing.JPanel jPanel4;
    javax.swing.JPanel jPanel5;
    javax.swing.JPanel jPanel6;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JScrollPane jScrollPane3;
    javax.swing.JScrollPane jScrollPane4;
    javax.swing.JScrollPane jScrollPane5;
    javax.swing.JPopupMenu.Separator jSeparator1;
    javax.swing.JSeparator jSeparator2;
    javax.swing.JSeparator jSeparator3;
    javax.swing.JSeparator jSeparator4;
    javax.swing.JSeparator jSeparator5;
    javax.swing.JTabbedPane jTabbedPane1;
    javax.swing.JTextField jTextField2;
    javax.swing.JLabel lImporteTotal;
    javax.swing.JLabel lTarifa;
    javax.swing.JLabel lblPremio1;
    javax.swing.JLabel lblPremio2;
    javax.swing.JLabel lblPremio3;
    javax.swing.JList listRemitentes;
    javax.swing.JMenu menuOrganizacion;
    javax.swing.JPanel pGrosor;
    javax.swing.JPanel pLienzoFirma;
    javax.swing.JProgressBar pbCalculo;
    javax.swing.JRadioButton rbInternacional;
    javax.swing.JRadioButton rbNacional;
    javax.swing.JRadioButton rbProvincial;
    javax.swing.JRadioButtonMenuItem rbmiEmpresarial;
    javax.swing.JRadioButtonMenuItem rbmiInternacional;
    javax.swing.JRadioButtonMenuItem rbmiNacional;
    javax.swing.JRadioButtonMenuItem rbmiPersonal;
    javax.swing.JRadioButtonMenuItem rbmiProvincial;
    javax.swing.JRadioButtonMenuItem rbmiPublica;
    javax.swing.JSlider slGrosor;
    javax.swing.JSlider sldHorizontal;
    javax.swing.JSlider sldVertical;
    javax.swing.JSpinner spinNumero;
    javax.swing.JTextArea taDetalleCalculo;
    javax.swing.JTextArea taDetallesRuta;
    javax.swing.JTextArea taImporteDetallado;
    javax.swing.JTextArea taTextoEtiqueta;
    javax.swing.JTextField tfCodigoCliente;
    javax.swing.JTextField tfDesNombreApellidos;
    javax.swing.JTextField tfMunicipio;
    javax.swing.JTextField tfRemDireccion;
    javax.swing.JTextField tfRemNombreApellidos;
    javax.swing.JTextField tfTarjeta;
    // End of variables declaration//GEN-END:variables
}
